name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * 1'

defaults:
  run:
    shell: bash
    working-directory: marketplace

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.15

      - name: Install dependencies
        run: npm install

      - name: Build & deploy
        run: npm run deploy
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
